/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDarkMode: typeof import('./components/Application/src/AppDarkMode.vue')['default']
    AppLocalePicker: typeof import('./components/Application/src/AppLocalePicker.vue')['default']
    BaseDialog: typeof import('./components/base-dialog/src/base-dialog.vue')['default']
    Hamburger: typeof import('./layout/components/Navbar/components/Hamburger.vue')['default']
    LoginForm: typeof import('./components/LoginForm/src/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./components/TransitionWrap/src/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/src/SvgIcon.vue')['default']
  }
}
